### ISSUE TITLE
OverflowError when trying to open ScalableBloomFilter object as a BloomFilter object

### ISSUE THREAD

**Issue by MPagel** [joseph-fox/python-bloomfilter#3]
obviously a lot of this is end-user error, but maybe the error thrown should be a bit more informative (header shouldn't match bloomfilter object type). Secondarily, maybe use itertools rather than xrange to avoid overflow errors if people really do have objects that big.

I'm using win8.1x64 and python 2.7

>   bl = BloomFilter.fromfile(bffp)
>   File "D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py", line 265, in fromfile
>     filter._setup(_unpack(cls.FILE_FMT, f.read(headerlen)))
>   File "D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py", line 150, in _setup
>     self.make_hashes = make_hashfuncs(self.num_slices, self.bits_per_slice)
>   File "D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py", line 77, in make_hashfuncs
>     salts = tuple(hashfn(hashfn(pack('I', i)).digest()) for i in range_fn(num_salts))
>   File "D:\Programs\Python\Python27\lib\site-packages\pybloom_live\utils.py", line 15, in range_fn
>     return xrange(_args)
> OverflowError: Python int too large to convert to C long
> 
> Frame fromfile in D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py at line 265
>         filter: <pybloom_live.pybloom.BloomFilter object at 0x03CEFB30>
>         cls: <class 'pybloom_live.pybloom.BloomFilter'>
>         f: <open file 'z:\\mpagel\\tek_all_download\\data\\JSATS_156029_id.hash', mode 'r+b' at 0x03D4C2E0>
>         headerlen: 40
>         n: -1
> Frame _setup in D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py at line 150
>         count: 2411
>         error_rate: -9.25596411573e+61
>         capacity: 5360614113
>         bits_per_slice: 5165088341154070528
>         self: <pybloom_live.pybloom.BloomFilter object at 0x03CEFB30>
>         num_slices: 8307539233996
> Frame make_hashfuncs in D:\Programs\Python\Python27\lib\site-packages\pybloom_live\pybloom.py at line 77
>         extra: 4
>         fmt_code: Q
>         total_hash_bits: 531682510975744
>         fmt: QQQQQQQQ
>         num_salts: 1038442404250
>         num_slices: 8307539233996
>         num_bits: 5165088341154070528
>         chunk_size: 8
>         hashfn: <built-in function openssl_sha512>
> Frame range_fn in D:\Programs\Python\Python27\lib\site-packages\pybloom_live\utils.py at line 15
>         args: List (size 1): (1038442404250L,)

init code for bloomfilter 

```
  bls = []
  for fn in [bffn_id, bffn_rh]:
    if (os.path.isfile(fn)):
      bffp = open(fn,"r+b")
      bl = ScalableBloomFilter.fromfile(bffp)
      bffp.close
      bls.append(bl)
#      del bl
    else:
      bls.append(ScalableBloomFilter(initial_capacity=nmost, error_rate=0.01))
  bl_rh = bls.pop()
  bl_id = bls.pop()

```

size of the saved bloomfilter files is 1-5KB.

**Comment by joseph-fox** [comment]
@MPagel  Got it fixed, updated the version number too. Please refer to https://pypi.python.org/pypi/pybloom_live/2.2.0.

**Comment by joseph-fox** [comment]
https://github.com/joseph-fox/python-bloomfilter/pull/4
