### ISSUE TITLE
pybloom.fromfile() raises deprecation warning from dependant bitarray

### ISSUE THREAD

**Issue by jamercee** [joseph-fox/python-bloomfilter#32]
The bitarray dependant library has deprecated the ``bitarray.length`` method in favor of ``self(len)`` (see [remove .length() method completely](https://github.com/ilanschnell/bitarray/commit/adaa069ca02db4f581fdea93bfedeffb56f880bc#diff-690c7fff5f864f485d5cb1b92c097561666604820d7a9541de76f185652a0a01).

The fix is quite simple. I've attached a patch to this email.

```
--- ../../../.pyenv/lib/python3.9/site-packages/pybloom_live/pybloom.py	2021-05-11 08:01:11.778010336 -0400
+++ pybloom.py	2021-05-11 09:48:04.340149673 -0400
@@ -213,8 +213,8 @@
         else:
             (filter.bitarray.frombytes(f.read()) if is_string_io(f)
              else filter.bitarray.fromfile(f))
-        if filter.num_bits != filter.bitarray.length() and \
-                (filter.num_bits + (8 - filter.num_bits % 8) != filter.bitarray.length()):
+        if filter.num_bits != len(filter.bitarray) and \
+                (filter.num_bits + (8 - filter.num_bits % 8) != len(filter.bitarray)):
             raise ValueError('Bit length mismatch!')
 
         return filter

```

[pybloom.txt](https://github.com/joseph-fox/python-bloomfilter/files/6460216/pybloom.txt)

**Comment by joseph-fox** [comment]
@jamercee, can you make a PR?

**Comment by joseph-fox** [comment]
https://pypi.org/project/pybloom-live/3.1.0/
