### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by void4** [joseph-fox/python-bloomfilter#34]
ScalableBloomFilter.fromfile() doesn't work in Python 3.9.5 since bitarray.length() was deprecated, which you already fixed in the repo. Could you create a new release for pip so the latest version can be installed this way?

**Comment by joseph-fox** [comment]
@void4 , 

Sorry, I forgot to release it. I will release it today.

**Comment by joseph-fox** [comment]
https://pypi.org/project/pybloom-live/3.1.0/

**Comment by void4** [comment]
Thank you :)
