### ISSUE TITLE
Kirsch-Mitzenmacher optimization 

### ISSUE THREAD

**Issue by RoyZhang7** [joseph-fox/python-bloomfilter#37]
Any plan on adding Kirsch-Mitzenmacher optimization?
https://www.eecs.harvard.edu/~michaelm/postscripts/tr-02-05.pdf

**Comment by joseph-fox** [comment]
@RoyZhang7, if you can add it and make a PR, I will merge it and release a new version.

**Comment by joseph-fox** [comment]
Close it as no replies received
