### ISSUE TITLE
Availability on conda?

### ISSUE THREAD

**Issue by alichaudry** [joseph-fox/python-bloomfilter#6]
I see that this is a more up-to-date fork of python-bloomfilter, but why not just have a PR to merge these changes back into the original repo? Also, would it be possible to have this available on the conda repo (conda-forge, probably)?

**Comment by joseph-fox** [comment]
I do not have the permission to merge the changes into the original repository, and the original author didn't respond. I have not yet had any plans on publishing it on `conda-forge` but it seems to be a good idea for the future work.
